name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
  push:
    paths-ignore:
      - 'docs/docs/**'
    branches:
      - main
      - dev

jobs:
  build:
    name: ğŸ› ï¸ Build Monorepo
    runs-on: ubuntu-latest
    steps:
      - name: ğŸš¨check out code
        uses: actions/checkout@v2

      - name: ğŸ”¨ Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          registry-url: 'https://registry.npmjs.org'

      - name: ğŸ”¨ Install pnpm
        run: npm install pnpm

      - name: ğŸ”¨ Install dependencies
        run: npm install --force

      - name: ğŸ¨ Run prettier
        run: npm run format-check

      - name: ğŸ¨ Run ESLint
        run: npm run lint

      - name: ğŸ‹ï¸â€â™‚ï¸ Build
        run: npm run build
